module.exports = {
    $addButton: "Add a Button Component to Message;$addButton[newRow (yes/no); customId; style (primary/secondary/success/danger/link); disabled (yes/no); emoji (optional); URL (optional, style='link' required)]",
    $addCmdReactions: "Add reactions to Author message",
    $addSelectMenuOption: "Adds an option to Select Menu component;$addSelectMenuOption[customId; min select (0-25, default 0); max select (1-25, default 1); disabled (yes/no); placeholder (optional)]",
    $allMembersCount: "Returns the number of users from all of Server the bot's in",
    $author: "Changes the author of an Embed;$author[text; iconURL (optional)]",
    $authorID: "Returns the ID of Author message or Reaction;$authorID",
    $botPing: "Returns the amount of time for message to be received by Client",
    $channelID: "Returns the ID of used Text channel;$channelID",
    $channelName: "Returns the name of Channel ID;$channelName or $channelName[channel ID]",
    $checkContains: "Returns a boolean if text contains provided fields;$checkContains[text;word1;word2;word3;...]",
    $color: "Changes the color of an Embed;$color[shortname color / hex / color number]",
    $description: "Changes the description of an Embed;$description[text]",
    $divide: "Divides an argument of number;$divide[1;2;3;...]",
    $djsEval: "Evaluates a snippet of JavaScript ( Nodejs ) code;$djsEval[code; returnResult (optional)]",
    $executionTime: "Returns the amount of time for above lines to finish.",
    $footer: "Changes the footer of an Embed;$footer[text; iconURL (optional)]",
    $getLength: "Returns the length of text;$getLength[text]",
    $guildID: "Returns the ID of the Server;$guildID",
    $ignoreErrors: "Ignore function errors and proceed until it's completion",
    $image: "Changes the image / video of an Embed;$image[fileURL]",
    $log: "Logs text into the Process Terminal;$log[text]",
    $message: "Returns the content or argument of Message Content;$message or $message[number] or $message[>number] or $message[<number] or $message[number>] or $message[number<] or $message[number-number]",
    $membersCount: "Returns the amount of members in the Server",
    $multi: "Multiplies an argument of number;$multi[1;2;3;...]",
    $ms: "Returns the Unix Timestamp of now Date",
    $newEmbed: "Creates a new Instance of embed",
    $newSelectMenu: "Adds a new Action Row and a Select Menu to Message;$newSelectMenu[customId; min value to select (0-25, default 0); max value to select (1-25, default 1); disabled (yes/no); placeholder]",
    $nomention: "Removes the ability to mention users, roles, etc",
    $onlyIf: "Blocks code execution if condition is not fullfilled;$onlyIf[value1==/!=/>/</>=/<=value2; errorMessage]",
    $ping: "Returns the amount of waiting time for a Request to be sent to Discord",
    $ram: "Returns the amount of RAM has been used by Nodejs runtime",
    $replaceText: "Replaces the < sample > to < replacement > from < parent > text for < how many >\nDefault is -1, which means 'all'.;$replaceText[parent; sample; replacement; how many (default = -1)]",
    $reply: "Replies to a message;$reply or $reply[messageID ; channelID (optional)]",
    $runtime: "Returns the uptime of Nodejs Runtime in ms",
    $serverName: "Returns the name of the Server;$serverName or $serverName[guild ID]",
    $serverOwner: "Returns the user ID who owns the Server;$serverOwner or $serverOwner[guild ID]",
    $strictErrors: "Enables strict errors, resulting more errors showing up",
    $maxRam: "Returns the maximum amount of RAM can be used",
    $splitText: "Retrieves an argument from Text Split;$splitText[number]",
    $sub: "Substracts an argument of number;$sub[1;2;3;...]",
    $sum: "Sumarizes an argument of number;$sum[1;2;3;...]",
    $textSplit: "Splits text from separator;$textSplit[text;separator (optional)]",
    $thumbnail: "Changes the thumbnail of an Embed;$thumbnail[imageURL]",
    $title: "Changes the title of an Embed;$title[text]",
    $uptime: "Returns the uptime of Client",
    $username: "Returns the Username of User ID;$username or $username[user ID]",
    $wait: "Holds code execution for some time;$replyIn[ms/duration]"
}